### PR TITLE
Fix entry points

### PR DESCRIPTION
**Pull request by wolsen**
While enabling noble, the entry_points are failing due to changes in the importlib apis from awhile back.

### CODE REVIEW

**Comment by hloeung** [comment]
Would https://github.com/canonical/charms.reactive/pull/251 help?

**Comment by wolsen** [comment]
> Would #251 help? Err, I mean #237

This would indeed address that bug.

**Review by ajkavanagh — APPROVED** [review]

**Review by ajkavanagh — APPROVED** [review]

**Comment by addyess** [comment]
Wow, super nice.  I needed this and came looking for it.  Thanks @ajkavanagh and @wolsen

**Comment by ajkavanagh** [comment]
> is there any reason this isn't published to pypi?

Ah, yes, I should probably do that.  I'll try to get it done tomorrow.

**Comment by addyess** [comment]
chances this still works in focal?

**Comment by ajkavanagh** [comment]
> chances this still works in focal?

It should do.  Although it was tested on 22.04, it passed tests with Python 3.7 and 3.8 and 3.8 was on focal (20.04).

**Comment by addyess** [comment]
@ajkavanagh i changed the wheelhouse on my charm to add this:

```diff
+  charms.reactive @ git+https://github.com/canonical/charms.reactive.git
```

and it works on noble and focal!  
NICE!

**Comment by addyess** [comment]
@ajkavanagh 
I don't want to speak for him but @johnsca may not wish to be a maintainer any longer on
https://pypi.org/project/charms.reactive/

Thanks for offering to publish a 1.5.3 or 1.6.0

**Pull request merged**
